name: Readme-Checker

# Triggers the workflow on push or pull request events but only for the "master" branch
on: [push, pull_request]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: markdownlint-cli2-action
      - uses: DavidAnson/markdownlint-cli2-action@v16.0.0
        with:
          globs: |
            *.md
            !test/*.md
