name: Markdown Lint
on:
  pull_request:
permissions:
  contents: write
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6
      - name: Markdown Lint
        uses: DavidAnson/markdownlint-cli2-action@6b51ade7a9e4a75a7ad929842dd298a3804ebe8b
        with:
          fix: true
          globs: |
            *.md
            !test/*.md
