name: Markdown Lint
on:
  pull_request:
permissions:
  contents: write
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6
      - name: Markdown Lint
        uses: DavidAnson/markdownlint-cli2-action@ded1f9488f68a970bc66ea5619e13e9b52e601cd
        with:
          fix: true
          globs: |
            *.md
            !test/*.md
